---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openlearn-backend-config
  labels:
    app: openlearn
    component: backend
data:
  # Application configuration
  ENABLE_SCHEDULER: "true"
  ENABLE_COMPRESSION: "true"
  DEBUG: "false"

  # Cache configuration
  CACHE_ENABLED: "true"
  CACHE_DEFAULT_TTL: "3600"

  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_PER_MINUTE: "60"

  # Search configuration
  ELASTICSEARCH_ENABLED: "true"

  # Logging
  LOG_LEVEL: "INFO"

  # CORS
  ALLOWED_ORIGINS: "https://openlearn.example.com,https://app.openlearn.example.com"

  # Health check timeouts
  HEALTH_CHECK_TIMEOUT: "5"
  DATABASE_HEALTH_TIMEOUT: "5"
  REDIS_HEALTH_TIMEOUT: "3"
  ELASTICSEARCH_HEALTH_TIMEOUT: "5"
