groups:
  - name: platform_critical
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

      - alert: DatabasePoolExhausted
        expr: db_connections_active >= 20
        for: 2m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection pool exhausted"
          description: "All 20 connections in use for 2+ minutes"

      - alert: ServiceDown
        expr: up{job="backend"} == 0
        for: 1m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "Backend service is down"
          description: "Service has been down for 1+ minute"

  - name: platform_warnings
    interval: 60s
    rules:
      - alert: CacheHitRatioLow
        expr: cache_hit_ratio < 0.70
        for: 10m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Cache hit ratio below threshold"
          description: "Hit ratio is {{ $value | humanizePercentage }} (threshold: 70%)"

      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "API response time degraded"
          description: "P95 latency is {{ $value }}s (threshold: 0.5s)"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Only {{ $value | humanizePercentage }} memory available"
